version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123! # Cambia esto si quieres
    ports:
      - "1433:1433"

  emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    depends_on:
      - sqlserver
    ports:
      - "5672:5672" # Puerto AMQP (Mensajería)
      - "5300:5300" # Puerto de administración
    environment:
      - ACCEPT_EULA=Y
      - SQL_SERVER=sqlserver
      - MSSQL_SA_PASSWORD=Password123!
    volumes:
      - ./Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json